easy_admin:
    entities:
        # List the entity class name you want to manage
        Bank:
            class: 'App\Entity\Bank'
            label: 'Bancos'
            list:
                title: 'Listado de bancos'
                fields: [ 'nombre', 'saldo' ]
                actions:
                    - { name: 'new' }
                    - { name: 'edit' }
                    - { name: 'show' }
                    - { name: 'cargar_saldo', type: 'route' }
            form:
                fields: [ 'nombre' ]
                title: 'Modificar %%entity_name%%'
            show:
                title: '%%entity_name%%'
                fields: [ 'nombre', { property: 'saldos', label: 'Saldos', template: 'saldos.html.twig' }, { property: 'saldosProyectados', label: 'Saldos proyectados', template: 'saldos.html.twig' }, 'movimientos' ]
        Debito:
            class: App\Entity\Movimiento
            label: 'Debitos'
            list:
                title: 'Listado de debitos'
                fields: [ 'concepto', 'fecha', 'importe', 'banco', { property: 'concretado', label: 'Pagado', type: 'boolean' } ]
                actions:
                    - { name: 'new', label: 'Nuevo Debito' }
                dql_filter: 'entity.importe < 0'
            form:
                fields: [ 'concepto', 'fecha', 'importe', 'banco' ]
            new:
                title: 'Nuevo Debito'
        Credito:
            class: App\Entity\Movimiento
            label: 'Creditos'
            list:
                title: 'Listado de creditos'
                fields: [ 'concepto', 'fecha', 'importe', 'banco', { property: 'concretado', label: 'Cobrado', type: 'boolean' } ]
                actions:
                    - { name: 'new', label: 'Nuevo Credito' }
                dql_filter: 'entity.importe > 0'
            form:
                fields: [ 'concepto', 'fecha', 'importe', 'banco' ]
            new:
                title: 'Nuevo Credito'
        GastoFijo:
            class: App\Entity\GastoFijo
            label: 'Gastos fijos'
            list:
                title: 'Listado de Gastos Fijos'
                fields: [ 'concepto', 'dia', 'fechaFin', 'importe', 'banco' ]
                actions:
                    - { name: 'new', label: 'Crear Gasto Fijo' }
            form:
                fields: [ 'concepto', 'dia',  { property: 'fechaFin', type: 'date' }, 'importe', 'banco' ]

#        - App\Entity\User
    site_name: '<img src="%router.request_context.base_url%/img/logo.png" /> Rotschild'
    design:
        brand_color: '#17509D'
        assets:
            js:
                - 'js/blasting.js'
        menu:
            - { label: 'Importar' }
            - { label: 'Extractos bancarios', route: 'import_bank_summaries', default: true }
            - { label: 'Cheques emitidos', route: 'import_issued_checks', default: true }
            - { label: 'Cheques aplicados', route: 'import_applied_checks', default: true }
            - { label: 'Conciliación' }
            - { label: 'Extractos bancarios', route: 'match_bank_summaries' }
            - { label: 'Cheques emitidos', route: 'confirm_issued_checks' }
            - { label: 'Cheques aplicados', route: 'process_applied_checks'}
            - { label: 'Movimientos'}
            - Debito
            - Credito
            - { label: 'Configuración' }
            - GastoFijo
            - Bank
    formats:
        date: 'd/m/Y'
