easy_admin:
    entities:
        # List the entity class name you want to manage
        Banco:
            class: 'App\Entity\Banco'
            label: 'Bancos'
            list:
                title: 'Listado de bancos'
                fields: [ 'nombre', 'saldo' ]
                actions: [ 'new', 'edit', 'show' ]
            form:
                fields: [ 'nombre', 'saldo' ]
                title: 'Modificar %%entity_name%%'
            show:
                title: '%%entity_name%%'
                fields: [ 'nombre', 'saldo', 'movimientos' ]
        DebitoProyectado:
            class: App\Entity\Movimiento
            label: 'Debitos proyectados'
            list:
                title: 'Listado de debitos proyectados'
                fields: [ 'concepto', 'fecha', 'importe', 'banco', { property: 'concretado', label: 'Pagado' } ]
                actions:
                    - { name: 'new', label: 'Nuevo Debito' }
                dql_filter: 'entity.concretado = 0 AND entity.importe < 0'
            form:
                fields: [ 'concepto', 'fecha', 'importe', 'banco' ]
            new:
                title: 'Nuevo Debito Proyectado'
        CreditoProyectado:
            class: App\Entity\Movimiento
            label: 'Creditos proyectados'
            list:
                title: 'Listado de creditos proyectados'
                fields: [ 'concepto', 'fecha', 'importe', 'banco', { property: 'concretado', label: 'Cobrado' } ]
                actions:
                    - { name: 'new', label: 'Nuevo Credito' }
                dql_filter: 'entity.concretado = 0 AND entity.importe > 0'
            form:
                fields: [ 'concepto', 'fecha', 'importe', 'banco' ]
            new:
                title: 'Nuevo Credito Proyectado'
        GastoFijo:
            class: App\Entity\GastoFijo
            label: 'Gastos fijos'
            list:
                title: 'Listado de Gastos Fijos'
                fields: [ 'concepto', 'dia', 'monto', 'banco' ]
                actions:
                    - { name: 'new', label: 'Crear Gasto Fijo' }

#        - App\Entity\User
    site_name: '<img src="/img/logo.png" /> BankMgr'
    design:
        brand_color: '#17509D'
        assets:
            js:
                - 'js/blasting.js'
    formats:
        date: 'd/m/Y'