easy_admin:
    entities:
        # List the entity class name you want to manage
        Bank:
            class: 'App\Entity\Bank'
            label: 'Bancos'
            list:
                title: 'Banks'
                fields: [ 'nombre', 'balance' ]
                actions:
                    - { name: 'new' }
                    - { name: 'edit' }
            form:
                fields: [ 'nombre' ]
                title: 'Modificar %%entity_name%%'
            show:
                title: '%%entity_name%%'
                fields: [ 'nombre', { property: 'saldos', label: 'Saldos', template: 'saldos.html.twig' }, { property: 'saldosProyectados', label: 'Saldos proyectados', template: 'saldos.html.twig' }, 'movimientos' ]
        Debit:
            class: App\Entity\Movimiento
            label: 'Debits'
            list:
                title: 'Debits'
                fields: [ 'concepto', 'fecha', 'importe', 'bank', { property: 'concretado', label: 'Pagado', type: 'boolean' } ]
                dql_filter: 'entity.importe < 0'
            form:
                fields: [ 'concepto', 'fecha', { property: 'importe', type: 'money', type_options: { currency: '%currency%' } }, 'bank' ]
            templates:
                new: 'new_tx.html.twig'
                edit: 'edit_tx.html.twig'
                ajax_layout: 'ajax_layout.html.twig'
        Credit:
            class: App\Entity\Movimiento
            label: 'Credits'
            list:
                title: 'Credits'
                fields: [ 'concepto', 'fecha', 'importe', 'bank', { property: 'concretado', label: 'Cobrado', type: 'boolean' } ]
                actions:
                    - { name: 'new', label: 'Nuevo Credit' }
                dql_filter: 'entity.importe > 0'
            form:
                fields: [ 'concepto', 'fecha', { property: 'importe', type: 'money', type_options: { currency: '%currency%' } }, 'bank' ]
            templates:
                new: 'new_tx.html.twig'
                edit: 'edit_tx.html.twig'
                ajax_layout: 'ajax_layout.html.twig'
        FixedExpense:
            class: App\Entity\FixedExpense
            controller: App\Controller\FixedExpenseController
            label: 'Gastos fijos'
            list:
                title: 'Gastos Fijos'
                fields: [ 'concepto', 'dia', { property: 'fechaFin', type: 'date' }, 'importe', 'bank' ]
                actions:
                    - { name: 'new', label: 'Crear Gasto Fijo' }
            form:
                fields: [ 'concepto', 'dia', { property: 'fechaInicio', type: 'date' }, { property: 'fechaFin', type: 'date' }, 'importe', 'bank' ]

    site_name: '<img src="%router.request_context.base_url%/img/logo.png" /> Rotschild'
    design:
        brand_color: '#17509D'
        assets:
            js:
                - 'js/blasting.js'
        menu:
            - { label: 'Bank summaries' }
            - { label: 'Importar', route: 'import_bank_summaries', default: true }
            - { label: 'Procesar', route: 'match_bank_summaries' }
            - { label: 'Cheques emitidos' }
            - { label: 'Importar', route: 'import_issued_checks' }
            - { label: 'Procesar', route: 'process_issued_checks' }
            - { label: 'Cheques recibidos' }
            - { label: 'Importar', route: 'import_applied_checks' }
            - { label: 'Procesar', route: 'process_applied_checks'}
            - { label: 'Banks' }
            - { label: 'Saldos', route: 'show_bank_balance' }
            - { label: 'Configuracion', entity: 'Bank' }
            - { label: 'Movimientos' }
            - FixedExpense
            - { label: 'Gasto Fijo total', route: 'fixed_expense_query' }
            - Debit
            - Credit
    formats:
        date: 'd/m/Y'
