easy_admin:
    entities:
        # List the entity class name you want to manage
        Banco:
            class: 'App\Entity\Banco'
            label: 'Bancos'
            list:
                title: 'Listado de bancos'
                fields: [ 'nombre', 'saldo' ]
                actions:
                    - { name: 'new' }
                    - { name: 'edit' }
                    - { name: 'show' }
                    - { name: 'cargar_saldo', type: 'route' }
            form:
                fields: [ 'nombre' ]
                title: 'Modificar %%entity_name%%'
            show:
                title: '%%entity_name%%'
                fields: [ 'nombre', { property: 'saldos', label: 'Saldos' }, 'movimientos' ]
        Debito:
            class: App\Entity\Movimiento
            label: 'Debitos'
            list:
                title: 'Listado de debitos'
                fields: [ 'concepto', 'fecha', 'importe', 'banco', { property: 'concretado', label: 'Pagado' } ]
                actions:
                    - { name: 'new', label: 'Nuevo Debito' }
                dql_filter: 'entity.importe < 0'
            form:
                fields: [ 'concepto', 'fecha', 'importe', 'banco' ]
            new:
                title: 'Nuevo Debito'
        Credito:
            class: App\Entity\Movimiento
            label: 'Creditos'
            list:
                title: 'Listado de creditos'
                fields: [ 'concepto', 'fecha', 'importe', 'banco', { property: 'concretado', label: 'Cobrado' } ]
                actions:
                    - { name: 'new', label: 'Nuevo Credito' }
                dql_filter: 'entity.importe > 0'
            form:
                fields: [ 'concepto', 'fecha', 'importe', 'banco' ]
            new:
                title: 'Nuevo Credito'
        GastoFijo:
            class: App\Entity\GastoFijo
            label: 'Gastos fijos'
            list:
                title: 'Listado de Gastos Fijos'
                fields: [ 'concepto', 'dia', 'importe', 'banco' ]
                actions:
                    - { name: 'new', label: 'Crear Gasto Fijo' }
            new:
                fields: [ 'concepto', 'dia', 'importe', 'banco' ]

#        - App\Entity\User
    site_name: '<img src="/img/logo.png" /> BankMgr'
    design:
        brand_color: '#17509D'
        assets:
            js:
                - 'js/blasting.js'
    formats:
        date: 'd/m/Y'
